
DECLARE @T TABLE (SourceSystemPrimaryKey VARCHAR(20),
					ColA VARCHAR(10),
					ColB VARCHAR(10),
					ColC VARCHAR(10),
					LoadId BIGINT)

INSERT INTO @T
SELECT '10', 'AAA', 'AAA', 'AAA', 1 UNION ALL
SELECT '20', 'AAA', 'AAA', 'AAA', 1 UNION ALL
SELECT '30', 'CCC', 'CCC', 'CCC', 1 UNION ALL
SELECT '40', 'EEE', 'EEE', 'EEE', 1 UNION ALL

SELECT '11', 'AAA', 'AAA', 'AAA', 2 UNION ALL
SELECT '21', 'BBB', 'BBB', 'BBB', 2 UNION ALL
SELECT '31', 'CCC', 'CCC', 'CCC', 2 UNION ALL
SELECT '11', 'CCC', 'CCC', 'CCC', 2 UNION ALL

SELECT '12', 'CCC', 'CCC', 'CCC', 3 UNION ALL
SELECT '13', 'EEE', 'EEE', 'EEE', 3 UNION ALL 
SELECT '14', 'EEE', 'EEE', 'EEE', 3 

SELECT	SourceSystemPrimaryKey
		,ColA
		,ColB
		,ColC
		,LoadId
		,RANK() OVER (PARTITION BY ColA,ColB,ColC ORDER BY LoadId DESC) R
		,ROW_NUMBER() OVER (PARTITION BY ColA,ColB,ColC,LoadId ORDER BY SourceSystemPrimaryKey DESC) RN
FROM @T
ORDER BY R, RN